version: "3.9"

services:
  init-frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "if [ ! -f package.json ]; then
        npm create vite@latest . -- --template react-ts &&
        npm install;
      fi"

  init-backend:
    image: python:3.11-slim
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "if [ ! -f main.py ]; then
        echo 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/\")\ndef read_root():\n    return {\"Hello\": \"World\"}' > main.py &&
        echo 'fastapi\nuvicorn\ndocker' > requirements.txt;
      fi"